version: "3"

services:
  mysql:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: local
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - 4000:8080
